version: '3.3'
services:
  api_despesamanager:  
    depends_on:
      - mysql_despesamanager
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "5000:5000"
    # expose:
    #   - '5000'
    # networks:
    #   - despesamanager
    container_name: api_despesamanager
    env_file:
      - ./env/backend.env
    restart: on-failure
  mysql_despesamanager:
    image: mysql/mysql-server
    container_name: mysql_despesamanager
    ports:
      - "3306:3306"
    # expose:
    #   - '3306'
    # networks:
    #   - despesamanager
    volumes:
    #- ./db_mysql/.data/db:/var/lib/mysql
      - /var/lib/mysql      
    #  - "./db_mysql/mysql-init.sh:/mysql-init.sh"
    #command: "sh /mysql-init.sh"
    #command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./env/mysql.env